<?php
/**
 * Coach Client Engine - License Issuer Tool (Standalone)
 * This tool is for the plugin owner only. Do not distribute.
 */

class CCE_License_Issuer {

    private $secret_salt = 'cce_ultra_secret_salt_12345';

    /**
     * Generate a new PRO license key.
     */
    public function generate_key($prefix = 'PRO-') {
        $random_part = bin2hex(random_bytes(8));
        $checksum = substr(md5($random_part . $this->secret_salt), 0, 4);
        return strtoupper($prefix . $random_part . '-' . $checksum);
    }

    /**
     * Verify if a key was generated by this tool.
     */
    public function verify_key($key) {
        $parts = explode('-', $key);
        if (count($parts) !== 3) return false;

        $random_part = strtolower($parts[1]);
        $checksum = strtolower($parts[2]);
        $expected_checksum = substr(md5($random_part . $this->secret_salt), 0, 4);

        return $checksum === $expected_checksum;
    }
}

// CLI Interface
if (php_sapi_name() === 'cli') {
    $issuer = new CCE_License_Issuer();
    echo "--- Coach Client Engine License Issuer ---\n";
    echo "1. Generate New License\n";
    echo "2. Verify License\n";
    $choice = readline("Choose an option: ");

    if ($choice == '1') {
        echo "Generated Key: " . $issuer->generate_key() . "\n";
    } elseif ($choice == '2') {
        $key = readline("Enter key to verify: ");
        if ($issuer->verify_key($key)) {
            echo "✅ Valid License Key\n";
        } else {
            echo "❌ Invalid License Key\n";
        }
    }
}
